version: "3.8"

services:
  app:
    container_name: product_app
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://db:5432/product_db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"